### PR TITLE
Can hide the table header

### PR DESCRIPTION
**Pull request by margarizaldi**
> _My situation requires me to have even more compact repeater, which might be needed by others too._

### CODE REVIEW

**Comment by margarizaldi** [comment]
Here's the result example:

image

**Comment by margarizaldi** [comment]
Let me know your review

**Comment by awcodes** [comment]
Thanks. I had to fix the columns widths for when the header was hidden, but works well.

**Comment by margarizaldi** [comment]
Awesome...
I have a new idea while you fixing that, but not sure you agree or not...

What if when the item number is 0, the whole table must not exist at all? so we won't have bodyless table there... I think that will have no problem with accessibility issue since there's nothing literally...

**Comment by awcodes** [comment]
I think the table headers are good for context, but let me think about it a little.

**Comment by margarizaldi** [comment]
> I think the table headers are good for context, but let me think about it a little.

Maybe add another <tbody> for empty state... Have a great weekend!

**Comment by awcodes** [comment]
I think this would be good to do similar to Filament tables where, there's a single row in the existing body that spans the column count plus the actions column (if they exist) that says something like 'No items' or something like that.

I just don't like the button being there by itself, centered with nothing but a field label all the way over to the left or right. Just my personal opinion though.

What do you think? Is that something you want to work on?

I'm happy to do it myself. :)

Good idea.

**Comment by margarizaldi** [comment]
I'll try. Thank you.

**Pull request merged**
